config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "splash#index"

  resources :groups, only: [:index, :show, :new, :create, :destroy] do
    resources :payments, only: [:index, :show, :new, :create]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, User

    return unless user.present?

    can :manage, Group, user_id: user.id
    can :manage, Payment, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :payments

  validates :name, presence: true
  validates :icon, presence: true

  def total_payments
    payments.sum(:amount)
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
  has_many :payments

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    @groups = current_user.groups.all
    @group = Group.find(params[:id])
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Category was successfully saved.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments or /payments.json
  def index
    @group = Group.find(params[:group_id])
    @payments = @group.payments.all.order(created_at: :desc)
  end

  # GET /payments/1 or /payments/1.json
  def show; end

  # GET /payments/new
  def new
    @payment = Payment.new
    @group = Group.find(params[:group_id])
  end

  # GET /payments/1/edit
  def edit; end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.user_id = current_user.id
    @payment.group_id = Group.find_by_id(params[:group_id]).id
    respond_to do |format|
      if @payment.save
        format.html { redirect_to group_payments_path(@payment.group_id), notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<i class="list-icon bi-list" role="img" aria-label="battery" style="font-size: 2.2rem"></i>
<i class="search-icon bi-search" role="img" aria-label="battery" style="font-size: 1.7rem"></i>
<h1 class="brand-text text-primary px-2 text-center border shadow-lg">Categories</h1>
<div class="p-2">
<% @groups.each do |group| %>
  <div class="card mb-3 bg-light" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-4 py-3">
          <img src=<%= group.icon%> class="img-fluid mx-auto d-block image"  height = "60" />
      </div>
      <div class="col-8">
        <div class="card-body">
          <%= link_to group_payments_path(group.id) do %>
            <h5 class="card-title"><%= group.name %></h5>
          <% end %>
          <small>Total payments: <%= group.total_payments %> $</small>
          <p class="card-text"><small class="text-muted"><%= group.created_at %></small></p>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>
<div class="px-2 text-center">
  <%= link_to "Add category", new_group_path, :class => "btn btn-primary" %>
</div>

app/views/groups/new.html.erb
 <%= link_to "Back", groups_path %>
<%= form_with model: @group, method: :post, local: true do |form| %>
    <div class="mb-3 p-2">
      <%= form.label :name, "Name", :class => "form-label" %>
      <%= form.text_field :name, placeholder: "Category", required: true, :class => "form-control" %>
    </div>

    <div class="mb-3 p-2">
      <%= form.label :icon, "Icon", :class => "form-label" %>
      <%= form.url_field :icon, placeholder: "Icon link", required: true, :class => "form-control" %>
    </div>

    <div class="p-2 text-center">
      <%= form.submit "Add Category", class: "btn btn-primary", disable_with: "Please wait..." %>
    </div>
<% end %>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div>
  <i class="reception bi bi-reception-4" role="img" aria-label="reception" style="font-size: 1.4rem"></i>
  <i class="battery bi bi-battery-half" role="img" aria-label="battery" style="font-size: 1.4rem"></i>
  </div>
   <% if notice %>
      <h4 class="notice"><%= notice %></h4>
    <% end %>
    <% if alert %>
      <h4 class="alert"><%= alert %></h4>
    <% end %>
      <% if user_signed_in? %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'logout-btn btn btn-light' %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Name:</strong>
    <%= payment.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= payment.amount %>
  </p>

</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
 
<i class="list-icon bi-list" role="img" aria-label="battery" style="font-size: 2.2rem"></i>
<i class="search-icon bi-search" role="img" aria-label="battery" style="font-size: 1.7rem"></i>
<%= link_to "Back", groups_path %>  
  <h1 class="brand-text text-primary px-2 text-center border shadow-lg">Transactions</h1>
<div class="p-2 text-center shadow-md">
  <h4>Total spent: <%= @group.total_payments %> $</h4>
</div>


<% @payments.each do |transaction| %>
  <div class="p-2">
    <div class="card p-2 bg-light">
      <div class="card-body">
        <h5 class="card-title"><%= transaction.name %></h5>
        <p class="card-text"><%= transaction.amount %>$</p>
        <p class="card-text"><small class="text-muted"><%= transaction.created_at %></small></p>
      </div>
    </div>
  </div>
<% end %>

<div class="p-2 text-center">
  <%= link_to "Add transaction", new_group_payment_path(@group.id), :class => "btn btn-primary" %>
</div>

app/views/payments/new.html.erb
 <%= link_to "Back", group_payments_path(@group.id) %>
<%= form_with model: @payment, url: group_payments_path, method: :post, local: true do |form| %>

    <div class="mb-3 p-2">
      <%= form.label :name, "Name", :class => "form-label" %>
      <%= form.text_field :name, placeholder: "Transaction Name", required: true, :class => "form-control" %>
    </div>

    <div class="mb-3 p-2">
      <%= form.label :amount, "Amount", :class => "form-label" %>
      <%= form.number_field :amount, placeholder: "Amount", required: true, :class => "form-control" %>
    </div>

    <div class="p-2 text-center">
      <%= form.submit "Save", class: "btn btn-primary", disable_with: "Please wait..." %>
    </div>

<% end %>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>

app/views/splash/index.html.erb
<div class='splash-body'>
<h1 class="main-logo logo-text text-primary text-center shadow-inset p-3 bg-body rounded">Danny's Budget <br> App</h1>
<div class="btns d-grid gap-2 text-bottom border"> 
  <%= link_to "Login", new_user_session_path, :class => "btn btn-primary btn-block"  %> 
  <%= link_to "Sign up", new_user_registration_path, :class => "btn btn-secondary btn-block"  %>
</div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Name, style: "display: block" %>
    <%= form.text_field :Name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.Name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_session_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>